spring.application.name=Fabric_Waste_Prediction
spring.datasource.url=jdbc:postgresql://localhost:5432/fabric_wastage_db
spring.datasource.username=postgres
spring.datasource.password=1234

# Optional JPA and Hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Use an appropriate dialect based on your PostgreSQL version
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

server.port=8080